name: project_eb_flutter
description: "A new Flutter project."
publish_to: 'none' # private package

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  cupertino_icons: ^1.0.8
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: SandollGothicNeo
      fonts:
        - asset: assets/fonts/AppleSDGothicNeoR.ttf

    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
  uses-material-design: true
  assets:
    - assets/images/
